# Generated by Django 5.0.3 on 2024-03-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=1200, null=True, verbose_name='title for seo')),
                ('seo_keyword', models.CharField(blank=True, max_length=1200, null=True, verbose_name='keyword for seo')),
                ('seo_alt', models.CharField(blank=True, max_length=1200, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=1200, null=True, verbose_name='description for seo')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stock_weight', models.PositiveBigIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product')),
            ],
        ),
    ]
