# Generated by Django 5.0.4 on 2024-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_instagram_rename_full_name_message_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
