# Generated by Django 5.0.4 on 2024-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_product_location_product_stock_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_bottom',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
